site_name: FUIRAX - Docs
site_url: https://furiax-know-your-fan.github.io/
repo_url: https://github.com/FURIAX-Know-Your-Fan
repo_name: cwtshh/FURIAX-Know-Your-Fan
theme:
  name: material
  favicon: assets/furia-logo.png
  logo: assets/furia-logo.png
  features:
    - navigation.indexes
    - navigation.instant
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Tecnologias: tecnologias.md
  - Fluxo de Usuário: fluxo.md
  - Fluxo de Dados: fluxo-dados.md
  - Funcionalidades: funcionalidades.md
  - Funcionalidades IA: func-ia.md
  - Setup da aplicação: setup.md